# ------ root_path/dataset_name ------
root_path: '../../DataSets/clip_fewshot'

# ------ Hyperparamters ------
search_hp: True

search_scale: [7, 7, 0.5]
search_step: [200, 20, 5]

init_beta: 1
init_alpha: 2
init_gamma: 0.1

eps: 0.001
training_feat_num: 500
training_free_feat_num: 500

w_training_free: [0.7, 0.3]
w_training: [0.2, 0.8]

# ------ Basic Config ------
dataset: 'imagenet'
backbone: 'RN50' # ViT-B/16

lr: 0.0001
augment_epoch: 10
train_epoch: 20
